apiVersion: v1
kind: Pod
metadata:
  name: counter4
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c, 'apt-get install -y npm; npm install -g artillery']
# apiVersion: v1
# kind: Pod
# metadata:
#   name: load-tester
# spec:
#   containers:
#   - name: load-test
#     image: ubuntu
    # args: [/bin/sh, -c, 'apt-get install -y npm && npm install -g artillery']
    # args: [/bin/sh, -c, 'i=0; while true; do echo "This is demo log $i: $(date)"; i=$((i+1)); sleep 1; done']