apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment-helm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: {{ .Values.sql.image.replicaCount }}
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: {{ .Values.sql.image.dockerHubId }}/{{ .Values.sql.image.name }}:{{ .Values.sql.image.tag }}
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: {{ .Values.sql.port }}
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "@Aa123456"
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service-helm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: {{ .Values.sql.port }}
      targetPort: {{ .Values.sql.port }}
  type: LoadBalancer
#      nodePort: 30202
#  type: NodePort